In [963]:
import pandas as pd

In [964]:
df = pd.read_csv("../data/loan_data.csv")
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y

In [965]:
df.shape

(381, 13)

In [966]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [967]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            381 non-null    object
 1   Gender             376 non-null    object
 2   Married            381 non-null    object
 3   Dependents         373 non-null    object
 4   Education          381 non-null    object
 5   Self_Employed      360 non-null    object
 6   ApplicantIncome    381 non-null    int64
 7   CoapplicantIncome  381 non-null    float64
 8   LoanAmount         381 non-null    float64
 9   Loan_Amount_Term   370 non-null    float64
 10  Credit_History     351 non-null    float64
 11  Property_Area      381 non-null    object
 12  Loan_Status        381 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 38.8+ KB

In [968]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,381.000000,381.000000,381.000000,370.000000,351.000000
mean,3579.845144,1277.275381,104.986877,340.864865,0.837607
std,1419.813818,2340.818114,28.358464,68.549257,0.369338
min,150.000000,0.000000,9.000000,12.000000,0.000000
25%,2600.000000,0.000000,90.000000,360.000000,1.000000
50%,3333.000000,983.000000,110.000000,360.000000,1.000000
75%,4288.000000,2016.000000,127.000000,360.000000,1.000000
max,9703.000000,33837.000000,150.000000,480.000000,1.000000

In [969]:
missing= df.isna().sum() 
percentage = ((missing/df.shape[0])*100).round(1)

In [970]:
missing_df = pd.DataFrame({"Missing Values": missing , "Percentage":percentage })
missing_df[missing_df['Missing Values'] > 0]

                  Missing Values  Percentage
Gender                         5         1.3
Dependents                     8         2.1
Self_Employed                 21         5.5
Loan_Amount_Term              11         2.9
Credit_History                30         7.9

In [971]:
df["Dependents"].unique()

array(['1', '0', '2', '3+', nan], dtype=object)

In [972]:
df["Self_Employed"].unique()

array(['No', 'Yes', nan], dtype=object)

In [973]:
df["Loan_Amount_Term"].unique()

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  84.,  12.,  36.])

In [974]:
# df['Dependents'] = df['Dependents'].fillna(df['Dependents'].mode()[0])
# df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
# df['Self_Employed'] = df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])
# df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0])
# df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mode()[0])

In [975]:
# #  Recommendation

# columns = [
#     "Dependents",
#     "Gender",
#     "Self_Employed",
#     "Loan_Amount_Term",
#     "Credit_History"
# ]

# for col in columns:
#     df[col] = df[col].fillna(df[col].mode()[0])

In [976]:
# df.isna().sum()

In [977]:
# df= df.drop(columns='Loan_ID')

In [978]:
# df.duplicated().sum()

In [979]:
# cols= df["Loan_Status"].value_counts()
# cols

In [980]:
# #  work on target variable 
# count = df["Loan_Status"].value_counts()
# percentage = ((count / len(df)) * 100).round(1)
# target_df = pd.DataFrame({
#     "Count": count,
#     "Percentage": percentage
# })

# target_df

In [981]:
categorical_features = [
    "Gender",
    "Married",
    "Dependents",
    "Education",
    "Self_Employed",
    "Property_Area",
    "Credit_History"
]

numerical_features = [
    "ApplicantIncome",
    "CoapplicantIncome",
    "LoanAmount",
    "Loan_Amount_Term"
]

target_feature = "Loan_Status"

In [982]:
# G_count = df['Gender'].value_counts()
# g_percent = ((G_count/len(df))*100).round(1)

In [983]:
# for i in categorical_features:
#     value_c = df[i].value_counts()
#     percent = ((value_c/len(df))*100).round(1)
    
#     summary= pd.DataFrame(
#         {
#             "Count": value_c,
#             "Percentage": percent
#         }
#     )
#     print(f"\n{'='*40}")
#     print(f"Feature:", i)
#     print(summary)

In [984]:
# #  Graphs 
# import matplotlib.pyplot as plt

# for i in categorical_features:
    
#     value_c = df[i].value_counts()
#     plt.figure(figsize=(4, 3))
#     plt.bar(value_c.index, value_c )
    
#     plt.xlabel(i)
#     plt.ylabel("Count")
#     plt.title(f"Distribution of {i}")
#     plt.show()

In [985]:
# df['Credit_History'].value_counts()

In [986]:
# # Numerical Feature Analysis
# for j in numerical_features:
#      information= df[j].describe()
#      print(f"\n{'='*40}")
#      print(f"Feature:", j)
#      print(information)

In [987]:
# #  graph numericals
# for k in numerical_features:
#     plt.figure(figsize=(3,3))
#     plt.boxplot(df[k])
#     plt.xlabel(k)
#     plt.show()

for col in numerical_features:

In [988]:
# for col in numerical_features:
#     Q1 = df[col].quantile(0.25)
#     Q3 = df[col].quantile(0.75)
#     IQR = Q3 - Q1
#     lower_bound = Q1 - (1.5 * IQR)
#     upper_bound = Q3 + (1.5 * IQR)
    
#     print("=" * 50)
#     print(f"Feature: {col}")
#     print(f"Q1           : {Q1}")
#     print(f"Q3           : {Q3}")
#     print(f"IQR          : {IQR}")
#     print(f"Lower Bound  : {lower_bound}")
#     print(f"Upper Bound  : {upper_bound}")

In [989]:
# for col in numerical_features:

#     Q1 = df[col].quantile(0.25)
#     Q3 = df[col].quantile(0.75)

#     IQR = Q3 - Q1

#     lower_bound = Q1 - (1.5 * IQR)
#     upper_bound = Q3 + (1.5 * IQR)

#     outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

#     print(f"{col}: {len(outliers)} outliers")

In [990]:
# pd.crosstab(df["Gender"], df["Loan_Status"])

In [991]:
# pd.crosstab(
#     df["Gender"],
#     df["Loan_Status"],
#     normalize="index"
# ).round(2)

In [992]:
# for feature in categorical_features:
#     print("=" * 50)
#     print(f"Feature: {feature}")
#     table = (pd.crosstab(df[feature], df["Loan_Status"], normalize='index')*100).round(1)
#     print(table)

In [993]:
# df.groupby("Loan_Status")["ApplicantIncome"].describe()

In [994]:
# for num in numerical_features:
#     print("=="*25)
#     print(f'frature = {num}')
#     comp = df.groupby("Loan_Status")[num].describe()
#     print(comp)

In [995]:
corr = df[numerical_features].corr()

corr

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term
ApplicantIncome,1.000000,-0.248693,0.270681,-0.109875
CoapplicantIncome,-0.248693,1.000000,0.114936,0.001906
LoanAmount,0.270681,0.114936,1.000000,0.123579
Loan_Amount_Term,-0.109875,0.001906,0.123579,1.000000

In [996]:
# #  Feature engineering 
# X = df.drop("Loan_Status", axis=1)

# y = df["Loan_Status"]

In [997]:
# print(X.shape)
# print(y.shape)

In [998]:
# y = y.map({
#     "Y":1,
#     "N":0
# })

In [999]:
# y.value_counts()

In [1000]:
# for col in categorical_features:
#     print("=="*20)
#     print(col)
#     print(X[col].unique())

In [1001]:
# binary_mapping = {
#     "Gender": {
#         "Male": 1,
#         "Female": 0
#     },
#     "Married": {
#         "Yes": 1,
#         "No": 0
#     },
#     "Education": {
#         "Graduate": 1,
#         "Not Graduate": 0
#     },
#     "Self_Employed": {
#         "Yes": 1,
#         "No": 0
#     }
# }

# for col, mapping in binary_mapping.items():
#     X[col] = X[col].map(mapping)

In [1002]:
X.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban

In [1003]:
# X["Dependents"] = X["Dependents"].replace({
#     "3+": "3"
# })

In [1004]:
# X["Dependents"] = X["Dependents"].astype(int)

In [1005]:
# X["Property_Area"].value_counts()

In [1006]:
# property_encoding = pd.get_dummies(
#     X['Property_Area']
# ).astype(int)

In [1007]:
# property_encoding.head()

In [1008]:
# X = X.drop("Property_Area", axis=1)

In [1009]:
# X.head()

In [1010]:
# X = pd.concat([X, property_encoding], axis=1)

In [1011]:
# X.head()

In [1012]:
# X.info()

In [1013]:
# from sklearn.preprocessing import StandardScaler
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(
#     X,
#     y,
#     test_size=0.2,
#     random_state=42
# )

In [1014]:
# print(X_train.shape)
# print(X_test.shape)

# print(y_train.shape)
# print(y_test.shape)

In [1015]:
# sclar = StandardScaler()
# X_train[numerical_features]= sclar.fit_transform(X_train[numerical_features])

In [1016]:
# X_test[numerical_features] = sclar.transform(
#     X_test[numerical_features]
# )

In [1017]:
# X_train[numerical_features].describe()

In [1018]:
# from sklearn.linear_model import LogisticRegression
# log_model = LogisticRegression(random_state=42)
# log_model.fit(X_train, y_train)

In [1019]:
# y_pred= log_model.predict(X_test)

In [1020]:
# from sklearn.metrics import confusion_matrix
# cm = confusion_matrix(y_test, y_pred)
# cm

In [1021]:
# from sklearn.metrics import accuracy_score

# accuracy = accuracy_score(y_test, y_pred)

# print(accuracy)

In [1022]:

# from sklearn.metrics import precision_score
# precision = precision_score(y_test, y_pred)

# print("Precision:", precision)

In [1023]:
# from sklearn.metrics import recall_score

# recall = recall_score(y_test, y_pred)

# print("Recall:", recall)

In [1024]:
# from sklearn.metrics import f1_score

# f1 = f1_score(y_test, y_pred)

# print("F1 Score:", f1)

In [1025]:
# from sklearn.metrics import (
#     accuracy_score,
#     precision_score,
#     recall_score,
#     f1_score
# )

# print("Accuracy :", accuracy_score(y_test, y_pred))
# print("Precision:", precision_score(y_test, y_pred))
# print("Recall   :", recall_score(y_test, y_pred))
# print("F1 Score :", f1_score(y_test, y_pred))

In [1026]:
# from sklearn.tree import DecisionTreeClassifier
# dt_model = DecisionTreeClassifier(max_depth=3,
#     random_state=42
# )
# dt_model.fit(X_train, y_train)

In [1027]:
# y_pred_dt = dt_model.predict(X_test)

In [1028]:
# from sklearn.metrics import (
#     accuracy_score,
#     precision_score,
#     recall_score,
#     f1_score
# )

# print("Accuracy :", accuracy_score(y_test, y_pred_dt))
# print("Precision:", precision_score(y_test, y_pred_dt))
# print("Recall   :", recall_score(y_test, y_pred_dt))
# print("F1 Score :", f1_score(y_test, y_pred_dt))

In [1029]:
# print("Training Accuracy:", dt_model.score(X_train, y_train))
# print("Testing Accuracy:", dt_model.score(X_test, y_test))

In [1030]:
# from sklearn.neighbors import KNeighborsClassifier
# knn_model = KNeighborsClassifier(
#     n_neighbors=5
# )
# knn_model.fit(X_train, y_train)
# y_pred_knn = knn_model.predict(X_test)

In [1031]:
# print("Accuracy :", accuracy_score(y_test, y_pred_knn))
# print("Precision:", precision_score(y_test, y_pred_knn))
# print("Recall   :", recall_score(y_test, y_pred_knn))
# print("F1 Score :", f1_score(y_test, y_pred_knn))

In [1032]:
# from sklearn.svm import SVC
# svm_model = SVC(random_state=42, kernel='linear', C=0.1)
# svm_model.fit(X_train, y_train)
# y_pred_svm = svm_model.predict(X_test)

In [1033]:
# print("Accuracy :", accuracy_score(y_test, y_pred_svm))
# print("Precision:", precision_score(y_test, y_pred_svm))
# print("Recall   :", recall_score(y_test, y_pred_svm))
# print("F1 Score :", f1_score(y_test, y_pred_svm))

In [1034]:
# from sklearn.ensemble import RandomForestClassifier
# rf_model = RandomForestClassifier(random_state=42, n_estimators=300,  max_depth=5)
# rf_model.fit(X_train,y_train)
# y_pred_rf = rf_model.predict(X_test)

In [1035]:
# from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# print("Accuracy :", accuracy_score(y_test, y_pred_rf))
# print("Precision:", precision_score(y_test, y_pred_rf))
# print("Recall   :", recall_score(y_test, y_pred_rf))
# print("F1 Score :", f1_score(y_test, y_pred_rf))

In [1036]:
# from xgboost import XGBClassifier

# xgb_model = XGBClassifier(random_state = 42, n_estimators=200, learning_rate = 0.2, max_depth=5)

# xgb_model.fit(X_train, y_train)

# y_pred_xgb = xgb_model.predict(X_test)

In [1037]:
# print("Accuracy :", accuracy_score(y_test, y_pred_xgb))
# print("Precision:", precision_score(y_test, y_pred_xgb))
# print("Recall   :", recall_score(y_test, y_pred_xgb))
# print("F1 Score :", f1_score(y_test, y_pred_xgb))

In [1038]:
# from sklearn.model_selection import cross_val_score
# scores = cross_val_score(
#     xgb_model,
#     X,
#     y,
#     cv=4,
#     scoring= 'accuracy'
    
# )
# print(scores)

In [1039]:
# print("Average Accuracy:", scores.mean())

In [1040]:
# from sklearn.model_selection import GridSearchCV
# param_grid= {
#     'n_estimators' : [100, 200, 300],
#     'max_depth' : [3,4,5,6,8,10],
#     'learning_rate': [0.1, 0.2, 0.3]
# }

# grid = GridSearchCV(
#     estimator=XGBClassifier(random_state=42),
#      param_grid=param_grid,
#     scoring="accuracy",
#     cv=5,
#     n_jobs=-1
# )

# grid.fit(X_train, y_train)

In [1041]:
# print(grid.best_params_)

In [1042]:
# print(grid.best_score_)

In [1043]:
# best_model = grid.best_estimator_

In [1044]:
# y_pred_g = best_model.predict(X_test)

In [1045]:
# print("Accuracy :", accuracy_score(y_test, y_pred_g))
# print("Precision:", precision_score(y_test, y_pred_g))
# print("Recall   :", recall_score(y_test, y_pred_g))
# print("F1 Score :", f1_score(y_test, y_pred_g))

In [1046]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from xgboost import XGBClassifier

In [1047]:
categorical_features = [
    "Gender",
    "Married",
    "Dependents",
    "Education",
    "Self_Employed",
    "Property_Area",
    "Credit_History"
]

numerical_features = [
    "ApplicantIncome",
    "CoapplicantIncome",
    "LoanAmount",
    "Loan_Amount_Term"
]

In [1048]:
# income_transformer = Pipeline(
#     steps=[
#         ("imputer", SimpleImputer(strategy="mean"))
#     ]
# )


# loan_transformer = Pipeline(
#     steps=[
#         ("imputer", SimpleImputer(strategy="median"))
#     ]
# )


# term_transformer = Pipeline(
#     steps=[
#         ("imputer", SimpleImputer(strategy="most_frequent"))
#     ]
# )

In [1049]:
# preprocessor = ColumnTransformer(
#     transformers=[

#         ("income",
#          income_transformer,
#          ["ApplicantIncome"]),

#         ("loan",
#          loan_transformer,
#          ["LoanAmount"]),

#         ("term",
#          term_transformer,
#          ["Loan_Amount_Term"])

#     ]
# )

In [1050]:
X = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]

In [1051]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [1052]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [1053]:
from sklearn.pipeline import Pipeline
from sklearn.impute import  SimpleImputer
numerical_transformer = Pipeline (
    steps= [
        ('imputer',SimpleImputer(strategy= 'median') )
        ]
)

In [1054]:
from sklearn.preprocessing import OneHotEncoder
categorical_transformer = Pipeline(
    [
        ('imputer', SimpleImputer(strategy= 'most_frequent')),
        ('encoder',OneHotEncoder(handle_unknown='ignore') )
        
    ]
)

In [1055]:
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [1056]:
model_pipeline = Pipeline(
    steps= [
        ('prpreprocessore', preprocessor),
        ('model', XGBClassifier(
            random_state=42,
            n_estimators=200,
            learning_rate=0.2,
            max_depth=5
        ))
    ]
)

In [1057]:
model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('prpreprocessore',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['ApplicantIncome',
                                                   'CoapplicantIncome',
                                                   'LoanAmount',
                                                   'Loan_Amount_Term']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Gender', 'M...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.2,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=200, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [1058]:
y_pred = model_pipeline.predict(X_test)

In [1059]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))

Accuracy : 0.8701298701298701
Precision: 0.8461538461538461
Recall   : 1.0
F1 Score : 0.9166666666666666
[[12 10]
 [ 0 55]]
              precision    recall  f1-score   support

           0       1.00      0.55      0.71        22
           1       0.85      1.00      0.92        55

    accuracy                           0.87        77
   macro avg       0.92      0.77      0.81        77
weighted avg       0.89      0.87      0.86        77

In [1060]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model_pipeline,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print(scores)
print(scores.mean())

[0.80519481 0.81578947 0.81578947 0.86842105 0.80263158]
0.8215652768284347

In [1061]:
f1_scores = cross_val_score(
    model_pipeline,
    X,
    y,
    cv=5,
    scoring="f1"
)

print(f1_scores)
print(f1_scores.mean())

[0.86956522 0.88135593 0.87931034 0.90384615 0.86486486]
0.8797885026266599

In [1062]:
import joblib
joblib.dump(
    model_pipeline,
    "loan_approval_model.pkl"
)

['loan_approval_model.pkl']

In [1063]:
loaded_model = joblib.load(
    "loan_approval_model.pkl"
)

In [1064]:
loaded_model

Pipeline(steps=[('prpreprocessore',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['ApplicantIncome',
                                                   'CoapplicantIncome',
                                                   'LoanAmount',
                                                   'Loan_Amount_Term']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Gender', 'M...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.2,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=200, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [1065]:
new_predictions = loaded_model.predict(X_test)

In [1066]:
accuracy_score(y_test, new_predictions)

0.8701298701298701

In [1067]:
import joblib

joblib.dump(model_pipeline, "loan_approval_model.pkl")

loaded_model = joblib.load("loan_approval_model.pkl")

In [1068]:
accuracy_score(
    y_test,
    loaded_model.predict(X_test)
)

0.8701298701298701